# Generated by Django 5.0.2 on 2026-02-13 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO country code', max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Wine Type',
                'verbose_name_plural': 'Wine Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='wines/%Y/%m/%d/')),
                ('year', models.IntegerField(help_text='Vintage year', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('alcohol_content', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('volume_ml', models.IntegerField(default=750, help_text='Bottle volume in ml')),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Available for purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='catalog.country')),
                ('wine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='catalog.winetype')),
            ],
            options={
                'verbose_name': 'Wine',
                'verbose_name_plural': 'Wines',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='catalog_win_slug_3fbf78_idx'), models.Index(fields=['wine_type', 'country'], name='catalog_win_wine_ty_da426c_idx'), models.Index(fields=['price'], name='catalog_win_price_2e9ef4_idx')],
            },
        ),
    ]
