# Generated by Django 6.0.2 on 2026-02-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AddField(
            model_name='order',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='По батькові'),
        ),
    ]
